### PR TITLE
Hide complex conditional logic from VideoModal component

### LINKED ISSUE #217: 🚀 Feature Request: Refactoring <LivestreamDetailsModal />
### Description
I found out `<LivestreamDetailsModal />` is combined many conditional logic in it such as `Clip` & `Livestream` while researching for #29 & #198 

It is difficult to read the condition during development. Maybe we could divide some code to other files and make the component display more precise purpose.

For example:
Screenshot 2024-02-21 at 14 51 26

We can use use component like `LivestreamModal` and `ClipModal` to specify different situation to render
```javascript
const Wrapper = ({ livestream, clip }) => {
  return livestream ? <LivestreamModal livestream={livestream} /> : <ClipModal  clip={clip} />
}

const  LivestreamModal = ({ livestream }) => {
  const url = getLivestreamUrl(livestream)
  const iconUrl = getLivestreamIconUrl(livestream)
  // Other codes
}

const  ClipModal = ({ clip }) => {
  const url = getClipUrl(clip)
  const iconUrl = getClipIconUrl(clip)
  // Other codes
}
```
The benefit is we can reduce complicate conditions and prevent too much `flag` like `isClip` to pass through functions.
The downside is we may have some duplicate code but I think we can refactor those code later after we ensure which code should be abstracted.

### PR DESCRIPTION
**Pull request by sruenwg**
Closes #217.

**What this PR solves / how to test:**
This is a refactoring of the VideoModal component (renamed from LivestreamDetailsModal), moving most of the conditional logic out into helper functions which now reside in `utils.ts`.
This abstracts away the complex logic which gets in the way when trying to understand the VideoModal component.

See [original issue](https://github.com/sugar-cat7/vspo-portal/issues/217) and [its comments](https://github.com/sugar-cat7/vspo-portal/issues/217#issuecomment-1976507171) for more context.

No functionality should be affected by this refactor.

Test cases:
- Video URL: 視聴 and 共有 buttons should point to correct URL
- Embed URL: video / site embed should be correct (should match with card and tab panel description)
- Chat embed URL: live Twitch and YouTube streams (and no other videos) should show the stream's chat in the chat tab
- Icon URL: avatar in card and in modal should be correct (should match with video embed and tab panel description)
- Chat tab styling should remain unchanged (should fill entire tab panel area regardless of screen size and orientation)

### CODE REVIEW

**Comment by sugar-cat7** [comment]
>To give an example, the current design of VideoPlayerOrLinkComponent is exactly what I would consider a lack of UI–logic separation. My suggestion would be to encapsulate the URL-forming logic in a helper (as I did here) but define that helper within the component rather than in utils.ts.

I agree that it's undesirable to have component-specific logic extracted as if it were a common procedure.

Therefore, I believe it's best to keep what can be contained within the component itself as contained as possible. Utils should only hold truly generic functions, such as those dealing with dates.

**Comment by sugar-cat7** [comment]
In my distant memory, I wanted to define components as completely separate from logic and as generic components. Within `features`, I aimed to create page-specific components by combining these generic components with logic, which would then be referenced from `pages`... I think. (I don't remember why it has become what it is now 🫠)

The structure I'm imagining is something like the one shown in the following link. (It may or may not be suitable since it's not Next.js...)
https://github.com/alan2207/bulletproof-react/tree/master/src

**Comment by ss77995ss** [comment]
> The structure I'm imagining is something like the one shown in the following link. (It may or may not be suitable since it's not Next.js...)

I think the folder structure is good for nextjs as long as we do not use their default file conventions.
ref: https://nextjs.org/docs/getting-started/project-structure#pages-routing-conventions

Not sure whether we have plan to change to `App` router but we can modify structure to fit their requirement later once we decide to migrate.

**Comment by sugar-cat7** [comment]
Thank you!
It seems best to aim for the structure of `/features` eventually. Let's create another issue to consider the units of division for features. (Personally, I have an image that pages and features correspond 1:1.)

**Review by sugar-cat7 — APPROVED** [review]
Thank you. 

It seems like aiming for the final structure under /features is a good idea. Let's create another issue to discuss the division units for features. (Personally, I have the impression that pages and features correspond one-to-one.)

As for this PR, it would be good to merge it here and gradually move from util to feature.

**Review by ss77995ss — APPROVED** [review]
LGTM 👍 !

**Pull request merged**
