### PR TITLE
Reduce Next.js warnings

### LINKED ISSUE #240: 📎 Remove Next.js-related console/terminal warnings
### Description

Next.js logs a number of warnings in terminal and/or the web console when running the app locally.
It would be nice if we could make the following changes to keep up to date with Next.js's best practices and to de-clutter our logs.
1. Replace `Image.layout` with `Image.style` or `Image.className`.
2. In the Next.js config, replace `images.domains` with `images.remotePatterns`.
3. Install `sharp` for image optimization. Related: #28

More details below:

1. Since v13, Next.js seems to have deprecated `Image.layout` in favor of the more canonical props `Image.style` or `Image.className`.
AFAICT this is just a change in API with no performance or behavioral change.
This is the warning that appears in dev mode when opening `/about`:
image

2. Since v14, Next.js seems to have deprecated the Next.js config property `images.domains` in favor of `images.remotePatterns`.
`remotePatterns` seems to allow for a more restrictive and thus secure configuration… though it might not be too useful for us.
This is logged in the command line both when running `dev` and `start`:
```
 ⚠ The "images.domains" configuration is deprecated. Please use "images.remotePatterns" configuration instead.
```

3. The following is logged when running `start`:
```
 ⚠ For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'npm i sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
```

### PR DESCRIPTION
**Pull request by sruenwg**
Closes #240.

**What this PR solves / how to test:**
This PR eliminates the Next.js warnings noted in #240.
1. Removed usage of `Image.layout` and used the `Image.style` prop instead to control the image size.
2. Replaced `images.domains` in the Next.js config with `images.remotePatterns`.
3. Added the `sharp` package for image optimization.

We still have a lot of warnings regarding the use of `Image.fill` (screenshot below), so I also tried to reduce the number of these warnings by removing the Image component from avatars (https://github.com/sugar-cat7/vspo-portal/commit/b466cd0b64babe4c063cf6d5d49f03b6d1cae724).
I can revert this if you suspect this hurts performance.

To test:
- On `dev`, opening `/about` (or any page) should not log any warnings to the web console regarding the use of the legacy `Image.layout` prop.
- When `start`ing the app, there should be no warning in the command line regarding the use of the deprecated config property `images.domains`.
- When `start`ing the app, there should be no warning in the command line prompting the user to install `sharp`.
- All images in the app should appear as they did before.
  - Images on `/about` should be displayed with the same dimensions as before.
  - No image with a valid URL should be blocked ([throwing a 400 error](https://nextjs.org/docs/pages/api-reference/components/image#remotepatterns) in the web console) from being shown.

### CODE REVIEW

**Comment by ss77995ss** [comment]
Maybe we could add `sizes="100vw"` for those `Image.fill` components to fix the warnings.
ref: https://github.com/vercel/next.js/discussions/40643#discussioncomment-7598340

According to next [docs](https://nextjs.org/docs/pages/api-reference/components/image#sizes) `100vw` is also their default value so I think the performance should be the same whether we add it or not
> If you don't specify a sizes value in an image with the fill property, a default value of 100vw (full screen width) is used.

**Comment by ss77995ss** [comment]
Oh I see! I thought they have already pushed the fixed version. Thanks for the information!

**Comment by ss77995ss** [comment]
I also not noticed they just released `14.1.1` three days ago 😅 
Not sure whether this is related but looks like they will also send warning if we set `100vw` in some situation

ref: https://github.com/vercel/next.js/blob/9fb18e673998635457903663205d10f6cc9b3849/packages/next/src/client/image-component.tsx#L124

**Review by sugar-cat7 — APPROVED** [review]
>But anyway, like you say, it looks like the 'fix' would still print a warning with 100vw, so I think we would need to determine a more meaningful sizes value if we really wanted to get rid of the warning.

Understood, thank you 🙇‍♀️

**Pull request merged**
